services:
  frontend:
    build: ./frontend
    container_name: laboratorio-frontend
    expose:
      - "80"
    networks:
      - laboratorio_net

  backend:
    build: ./backend
    container_name: laboratorio-backend
    expose:
      - "3000"
    volumes:
      - ./init:/init
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=laboratorio
    depends_on:
      - db
    networks:
      - laboratorio_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/status"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:latest
    container_name: laboratorio-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - laboratorio_net

  db:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_DATABASE=laboratorio
      - MARIADB_USER=root
      - MARIADB_PASSWORD=1234
    ports:
      - "3306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d  # <-- montar scripts de inicialización desde el directorio raíz 'init'
    networks:
      - laboratorio_net
    restart: unless-stopped

networks:
  laboratorio_net:
    driver: bridge